# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='party',
            name='category',
        ),
        migrations.RemoveField(
            model_name='party',
            name='invitation_opened',
        ),
        migrations.RemoveField(
            model_name='party',
            name='is_invited',
        ),
        migrations.RemoveField(
            model_name='party',
            name='type',
        ),
        migrations.AddField(
            model_name='party',
            name='relation',
            field=models.CharField(choices=[('friends', 'friends'), ('family', 'family')], default='friends', max_length=10),
        ),
    ]
