# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20180212_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='has_plus_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='plus_one_attending',
            field=models.BooleanField(default=False),
        ),
    ]
