# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20180212_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='invitation_opened',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
