# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_auto_20180225_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='invitation_opened',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
