# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_party_invitation_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='plus_one_attending',
            field=models.NullBooleanField(default=None),
        ),
    ]
