# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_auto_20180225_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='relation',
        ),
        migrations.AlterField(
            model_name='party',
            name='category',
            field=models.CharField(choices=[('friends', 'friends'), ('family', 'family')], default='friends', max_length=10),
        ),
        migrations.AlterField(
            model_name='party',
            name='invitation_id',
            field=models.CharField(db_index=True, default=None, max_length=32, unique=True),
        ),
    ]
