# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0021_auto_20180225_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='invitation_id',
            field=models.CharField(db_index=True, default='', max_length=32, unique=True),
        ),
    ]
