# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_party_invitation_opened'),
        ('guests', '0022_auto_20180225_2018'),
    ]

    operations = [
    ]
